const express=require('express');const helmet=require('helmet');const rateLimit=require('express-rate-limit');
const {Client,GatewayIntentBits,Partials}=require('discord.js');const config=require('./config');const {query}=require('./db');const cfg=require('./services/config');const oauth=require('./services/oauth');const logs=require('./services/logging');const worker=require('./services/memberWorker');const {handle}=require('./commands');
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent],partials:[Partials.Channel]});client.pendingConfirm=new Map();
const app=express();app.use(helmet());app.use(rateLimit({windowMs:60_000,max:60,standardHeaders:true,legacyHeaders:false}));
app.get('/',(_q,r)=>r.type('text').send('Payout Central OAuth2 service is running.'));
app.get('/oauth/callback',async(req,res)=>{try{if(!req.query.code||!req.query.state)return res.status(400).send('Missing OAuth2 code or state.');const context=await oauth.consumeState(req.query.state);if(!context)return res.status(400).send('Invalid or expired OAuth2 state.');const [userId,guildId]=String(context).split('|');const t=await oauth.token(req.query.code);const u=await oauth.me(t.access_token);if(u.id!==userId)return res.status(400).send('OAuth2 identity mismatch.');await oauth.save(u,t);if(guildId&&config.verifiedRoleId){const g=await client.guilds.fetch(guildId).catch(()=>null);const member=await g?.members.fetch(u.id).catch(()=>null);if(member&&!member.roles.cache.has(config.verifiedRoleId))await member.roles.add(config.verifiedRoleId).catch(()=>{});await query('UPDATE users SET verified=true WHERE user_id=$1',[u.id])}res.type('html').send('<!doctype html><meta charset="utf-8"><title>Verified</title><style>body{font-family:sans-serif;max-width:700px;margin:60px auto;padding:20px}</style><h1>Verification complete</h1><p>Your Discord account has been authorized successfully. You may close this page and return to Discord.</p>')}catch(e){console.error(e);await logs.send(client,'errors',`OAuth callback error: ${e.message}`);res.status(500).send('OAuth2 authorization failed.')}});
async function syncGuild(g){await query(`INSERT INTO servers(server_id,name,member_count,joined_at,updated_at) VALUES($1,$2,$3,NOW(),NOW()) ON CONFLICT(server_id) DO UPDATE SET name=EXCLUDED.name,member_count=EXCLUDED.member_count,updated_at=NOW()`,[g.id,g.name,g.memberCount])}
client.once('ready',async()=>{console.log(`Logged in as ${client.user.tag}`);for(const g of client.guilds.cache.values())await syncGuild(g);worker.start(client);console.log(`Ready in ${client.guilds.cache.size} guild(s).`)});
client.on('guildCreate',async g=>{await syncGuild(g);await logs.send(client,'server',`Bot joined ${g.name} (${g.id}).`)});
client.on('guildDelete',async g=>{await query('UPDATE servers SET updated_at=NOW() WHERE server_id=$1',[g.id]);await logs.send(client,'server',`Bot left ${g.name} (${g.id}).`)});
client.on('messageCreate',m=>handle(m,client));
client.on('interactionCreate',async i=>{if(!i.isButton())return;const [action,id]=i.customId.split(':');const item=client.pendingConfirm.get(id);if(!item)return i.reply({content:'This confirmation has expired.',ephemeral:true});if(item.userId!==i.user.id)return i.reply({content:'Only the administrator who started this action can confirm it.',ephemeral:true});client.pendingConfirm.delete(id);if(action==='decline')return i.update({content:'Action cancelled.',components:[]});try{const result=await item.action();return i.update({content:String(result),components:[]})}catch(e){console.error(e);await logs.send(client,'errors',`Confirmation action: ${e.message}`);return i.update({content:'The action failed and has been logged.',components:[]})}});
client.on('error',e=>logs.send(client,'errors',`Discord client error: ${e.message}`));process.on('unhandledRejection',e=>{console.error(e);logs.send(client,'errors',`Unhandled rejection: ${e?.message||e}`)});
app.listen(config.port,()=>console.log(`OAuth2 server listening on ${config.port}`));client.login(config.token);
