const crypto=require('crypto');const config=require('../config');const {query}=require('../db');const {encrypt,decrypt}=require('./crypto');
function url(state){const p=new URLSearchParams({client_id:config.clientId,response_type:'code',redirect_uri:config.redirectUri,scope:config.scopes.join(' '),state});return `https://discord.com/oauth2/authorize?${p}`}
async function token(code){const body=new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,grant_type:'authorization_code',code,redirect_uri:config.redirectUri});const r=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`OAuth token exchange ${r.status}`);return r.json()}
async function me(access){const r=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw new Error(`OAuth user ${r.status}`);return r.json()}
function state(userId,context=''){const s=crypto.randomBytes(32).toString('hex');return query('INSERT INTO oauth_states(state,user_id) VALUES($1,$2)',[s,context?`${userId}|${context}`:userId]).then(()=>s)}
async function consumeState(s){const r=await query('SELECT user_id,created_at FROM oauth_states WHERE state=$1',[s]);if(!r.rowCount)return null;await query('DELETE FROM oauth_states WHERE state=$1',[s]);if(Date.now()-new Date(r.rows[0].created_at).getTime()>config.stateTtl*1000)return null;return r.rows[0].user_id}
async function save(user,t){await query(`INSERT INTO users(user_id,username,verified) VALUES($1,$2,true) ON CONFLICT(user_id) DO UPDATE SET username=EXCLUDED.username,verified=true`,[user.id,user.username]);await query(`INSERT INTO oauth_authorizations(user_id,scope,access_token,refresh_token,expires_at,revoked_at) VALUES($1,$2,$3,$4,NOW()+($5||' seconds')::interval,NULL) ON CONFLICT(user_id) DO UPDATE SET scope=EXCLUDED.scope,access_token=EXCLUDED.access_token,refresh_token=EXCLUDED.refresh_token,expires_at=EXCLUDED.expires_at,last_seen_at=NOW(),revoked_at=NULL`,[user.id,t.scope||config.scopes.join(' '),encrypt(t.access_token),t.refresh_token?encrypt(t.refresh_token):null,Number(t.expires_in||604800)]);const n=Number((await query(`SELECT COUNT(*)::int c FROM oauth_authorizations WHERE revoked_at IS NULL`)).rows[0].c);await query(`UPDATE oauth_stats SET total_authorizations=total_authorizations+1,all_time_peak=GREATEST(all_time_peak,$1) WHERE id=1`,[n])}
async function counts(){const c=Number((await query(`SELECT COUNT(*)::int c FROM oauth_authorizations WHERE revoked_at IS NULL`)).rows[0].c);const d=Number((await query(`SELECT COUNT(*)::int c FROM oauth_authorizations WHERE authorized_at>=NOW()-INTERVAL '24 hours'`)).rows[0].c);const p=Number((await query('SELECT all_time_peak FROM oauth_stats WHERE id=1')).rows[0]?.all_time_peak||0);return {current:c,last24:d,peak:p}}
async function eligible(){return (await query(`SELECT oa.user_id,oa.access_token,oa.refresh_token,oa.expires_at FROM oauth_authorizations oa JOIN stock s ON s.user_id=oa.user_id WHERE oa.revoked_at IS NULL AND s.assigned=false`)).rows}
async function revoke(userId){await query('UPDATE oauth_authorizations SET revoked_at=NOW() WHERE user_id=$1',[userId]);await query('DELETE FROM stock WHERE user_id=$1',[userId])}
module.exports={url,state,consumeState,token,me,save,counts,eligible,revoke,decrypt};
